name: API Security Testing Workflow

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check API Endpoint Integrity
        run: bash scripts/check_api_endpoint.sh

      - name: Run Tests
        run: bash scripts/run_tests.sh

      - name: Prevent Unauthorized Changes
        if: github.event_name == 'pull_request'
        run: bash scripts/prevent_unauthorized_changes.sh
